### ISSUE TITLE
Nesting x-show does not work properly

### ISSUE THREAD

**Issue by digilist** [alpinejs/alpine#179] opened 2020-02-13 18:55 UTC
https://codepen.io/digilist/pen/jOPWMoz

Checking the first checkbox does not have any effect when the inner div with x-show is defined. Removing it fixes the first x-show/checkbox effect.

What's also interesting: Unchecking the first checkbox and then unchecking the second checkbox leads to the desired behavior, so the checks are only executed when the inner input changes.

For me it looks like there is some confusion with these nested x-shows.

**Comment by SimoTod** [comment] 2020-02-13 19:57
It looks like a regression introduced in the last release. v1.10.1 seems to work correctly.

**Comment by benfurfie** [comment] 2020-02-14 12:42
Yup. Also experiencing the behavior.

**Comment by calebporzio** [comment] 2020-02-14 18:47
Good catch, thanks for the succinct little codepen.

Should be fixed in v1.11.1

Thanks!

**Closed by calebporzio** 2020-02-14 18:47 UTC

**Comment by digilist** [comment] 2020-02-16 19:41
Thank you! :relaxed:
