### ISSUE TITLE
Issues with setTimeout

### ISSUE THREAD

**Issue by rusya1313** [alpinejs/alpine#83] opened 2020-01-15 01:28 UTC
I tried to create a simple TODO app and got my browser freezing.
[Violation] 'setTimeout' handler took <N>ms
Please have a look here: https://codesandbox.io/s/priceless-hofstadter-ijk3t

**Comment by calebporzio** [comment] 2020-01-15 14:24
Hmm... I don't see that problem at all when I load it in the sandbox. Do you get the same results in a CodePen?

**Comment by Rusya13** [comment] 2020-01-15 14:31
@calebporzio  Have you tried to add more than 8 tasks? It doesn't matter where. On my local environments the same result..

**Comment by calebporzio** [comment] 2020-01-15 15:19
I see the performance issue now. You are doing some pretty crazy things in that component. The problem is somehow the Proxy is getting nested an exponential number of times and creating this issue.

I can't pinpoint the exact problem, but here's a better way to write it that can handle large amounts of tasks:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script
      src="dist/alpine.js"
      defer
    ></script>

    <title>Document</title>
  </head>
  <body>
    <div x-data="pageData()">
        <section id="add-task-container">
          <form x-on:submit.prevent>
            <input type="text" x-model="newLabel" />
            <button type="submit" x-on:click="addTask()">
              Add task
            </button>
          </form>
        </section>
        <div x-html="renderTasks()"></div>
    </div>
    <script>
      var store = {};

      function registerStore(data, name) {
        store[name] = data;
      }

      function pageData() {
        return {
            tasks: [],
            newLabel: '',
            addTask() {
                this.tasks.push({
                    id: Math.random().toString(36).substr(2, 9),
                    label: this.newLabel,
                    done: false,
                })

                this.newLabel = ''
            },
            renderTasks() {
                return this.tasks.length === 0 ? '' : this.tasks.map(task => {
                        return `
                            <div>
                                ${task.label}
                            </div>
                        `;
                    })
                    .join("");

            }
        };
      }
    </script>
  </body>
</html>
```

If you can pin-point the culprit in your code and isolate it to a simple code sample, we can open up this box again, but for now, I'm closing this.

**Closed by calebporzio** 2020-01-15 15:19 UTC

**Comment by Rusya13** [comment] 2020-01-26 00:20
I saw another example on Twitter:
https://twitter.com/alexfwulf/status/1221191875379507200
Tried to play with it on Codepen (https://codepen.io/wulfheart/pen/povYZZN?editors=0000) and locally.
The problem with setTimout still exists:
<img width="596" alt="Screen Shot 2020-01-26 at 11 16 15 am" src="https://user-images.githubusercontent.com/10187260/73128994-d6393200-402d-11ea-805d-6421d75b2a2d.png">

**Comment by rusya1313** [comment] 2020-01-26 02:07
It is in the sandbox too, but you can't see the warnings there. You can try
it by clicking more than 10 times on different sort buttons. Each time it
will increase the delay before re-render. It is "debounce" function where
it happens. I think the problem is with the Proxy objects which still exist
in the memory for old Components(in this case each table row).

**Comment by rusya1313** [comment] 2020-02-04 05:43
The issue still persist in latest release 1.9.7. I got the example from this article:
https://www.mejlak.com/blog/alpinejs-not-another-javascript-framework/
Example: https://codesandbox.io/embed/alpinejs-simple-todo-wh1zf?fontsize=14&hidenavigation=1&theme=dark

Step 1:
Create 15 todos
![Screen Shot 2020-02-04 at 4 38 37 pm](https://user-images.githubusercontent.com/38521803/73717201-32f2c600-476d-11ea-8a07-1d059697462a.png)

Step 2:
Try to delete them

After deleting 8th it is becoming a nightmare.

**Comment by SimoTod** [comment] 2020-02-04 21:32
@rusya1313 Have you found what is slowing down the execution? 
From a quick look, it doesn't seem to multiplies the proxies anymore so there must something else.

**Comment by SimoTod** [comment] 2020-02-04 22:48
I think I figured out what it's going on.
Every time we rebuild the list, the code generates a new proxy for each item so, although they are not nested, they still get allocated in memory.

I think it's worth to reopen this bug.

 cc @calebporzio I think the problem is line 116, every time we access a property that is an object, Alpine creates a new proxy for it and they keep observing the variable. 
The x-for just makes it obvious but it would happen with any objects if the component does a lot of access to an object variable.
The code should somehow intercept the call before it gets that far into the get trap, maybe something like `if (target["$isAlpineProxy"]) return target["$originalTarget"][key]`.

**Comment by SimoTod** [comment] 2020-02-05 20:00
@rusya1313 Can you do me a favour? Can you stress test this version of Alpine and let me know if there are still performance issues, please?
https://cdn.jsdelivr.net/gh/simotod/alpine@feature/proxy-refactoring/dist/alpine.js

I forked your example and added the patched version and it looks way better to me: https://codesandbox.io/s/alpinejs-simple-todo-uxe7b

**Comment by rusya1313** [comment] 2020-02-11 06:31
@SimoTod Sorry, I just saw your message. Looks good to me. No freezing.
There is one thing, I don't understand: where are you setting "$isAlpineProxy"  key?

**Comment by SimoTod** [comment] 2020-02-11 08:19
@rusya1313 it's in the proxy handler, get trap. That PR has already been merged. 
If you use version 1.10.1 for your project, it should work without freezing.
