### ISSUE TITLE
Reactivity lost on v1.5 → v1.6 when binding to a function returning boolean

### ISSUE THREAD

**Issue by johndoe75** [alpinejs/alpine#67] opened 2020-01-10 21:16 UTC
This was working in version smaller or equal to 1.5.0 and since 1.6.0 it's no longer working:

```html
<div x-data="test(true)">

  <button @click="toggle()">Press me</button>

  <input type="text" x-bind:value="isSet" />

  <input type="text" x-bind:value="getIsSet()" />

</div>
```

```javascript
function test(status) {

  return {
    isSet: !!status,
    toggle() {
      this.isSet = !this.isSet
    },
    getIsSet() {
      return this.isSet
    }
  }

}
```

Reading the `isSet` value from the data-set is reactive and updated correct.  But binding the return value from `getIsSet()`, it's not updated – even though is initialized correct.  When running the same code with v1.5, it's working as expected.

You can test it in this [fiddle](https://jsfiddle.net/johndoe75/7wpae53j/4/).

**Comment by jreviews** [comment] 2020-01-10 21:21
I think this may be a duplicate of #66

**Comment by johndoe75** [comment] 2020-01-10 21:39
You're right.  Looks like 66 was published while I was working on the fiddle. :)

**Comment by calebporzio** [comment] 2020-01-12 05:34
Should be good now in 1.8.0

**Closed by calebporzio** 2020-01-12 05:34 UTC
