### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ahawlitschek** [alpinejs/alpine#697] opened 2020-08-09 23:25 UTC
When Using chart.js with multiple Axis, this error appears. 
When I try to add the sample from chart.js with plain javascript the error does not appear. 

I already tried to use a javascript function instead of writing the script directly into x-init, but the error remains the same. 
Is there some kind of limit in alpine?

**Comment by ahawlitschek** [comment] 2020-08-10 08:51
After some more testing I discovered, that this issues seems to be related to livewire. 
When using a Route::view instead of livewire, the issue does not apperar

**Comment by HugoDF** [comment] 2020-08-10 14:23
Are we fine to close this issue if it's Livewire specific?

**Comment by ahawlitschek** [comment] 2020-08-11 08:59
Yes, sure.
Quite curious, but I need to ask Caleb

**Comment by HugoDF** [comment] 2020-08-11 19:17
> Yes, sure.
> Quite curious, but I need to ask Caleb

It would help to have a reproduction case

**Comment by ahawlitschek** [comment] 2020-08-12 08:01
I am going to create one, as soons as I got time for it

**Comment by ahawlitschek** [comment] 2020-08-13 09:18
So, took me some time to reproduce it, but here we go:
https://github.com/ahawlitschek/call-stack-size-error-example

There seems to be 3 conditions for the bug to appear:

1. There is an alpine on top
2. A blade if
3. Another alpine component responsible for showing

In the real world application, I encountered this problem, the layout is:
A Google Map where you can select markers (alpine component on top is responsible for loading the map and handling events)
blade if to show a detail page on the right side
Tabs with Alpine that shows the chart only if the Overview tab is selected.

The nesting of alpine components seems to be responsible. 
I know,  I could restructure it to avoid nesting. 

But can you tell me, why nesting alpine components is leading to that issue?

**Comment by ahawlitschek** [comment] 2020-08-27 08:54
Thanks for digging into this issue!

I have already refactored my code to avoid this issue. 
But was quite curious about what caused it and hoped to help the community with reporting it.

I will try this the next time I need to use chart.js in an livewire/alpine project

**Comment by HugoDF** [comment] 2020-11-03 16:54
I'll close this for now since @ahawlitschek has a workaround, if anyone runs into the same issue, feel free to reopen/create a new issue linking to this one if the suggested workarounds don't work.

**Closed by HugoDF** 2020-11-03 16:54 UTC

**Comment by ju5t** [comment] 2021-07-09 18:08
@ahawlitschek would you mind sharing what it is you did? We had a working version in v2 but when we switched to v3 it broke and gave back the same error as you shared.

I'm hoping what you did could solve it for us too.
