### ISSUE TITLE
IE11 - Expected Identifier Error

### ISSUE THREAD

**Issue by keyurshah** [alpinejs/alpine#259] opened 2020-03-09 19:08 UTC
I'm getting an error 

```
Script1010: Expected Identifier
alpine-ie11.js (5918,9)
```

which points to the last line in the block

```
  /**
   * Copyright (C) 2017 salesforce.com, inc.
   */
  const { isArray: isArray$1 } = Array;
```

I tried adding in the head tag the following based on others receiving this error, but no luck:

```
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

Wondering if anyone else is receiving this error as well?

**Comment by heybourn** [comment] 2020-03-09 20:17
Yup, just got this too!

**Comment by HugoDF** [comment] 2020-03-09 22:05
That looks like a destructuring assignment that didn't get compiled away 👀

**Comment by HugoDF** [comment] 2020-03-09 22:21
@heybourn @keyurshah Could you take the code in that PR for a spin?

It's available through JSDeliver at `https://cdn.jsdelivr.net/gh/HugoDF/alpine@fix-compile-membrane/dist/alpine-ie11.js`, thanks for reporting this.

**Comment by heybourn** [comment] 2020-03-09 22:33
Seems to have removed the initial issue, however I'm now getting an error on IE that looks like this:

`Unhandled promise rejection TypeError: Proxy polyfill does not support trap 'originalTarget'`

Probably unrelated, but any ideas as to what it could be caused by?

**Comment by HugoDF** [comment] 2020-03-09 22:48
Sounds like it has something to do this the following: https://developer.mozilla.org/en-US/docs/Web/API/Event/originalTarget

Weird that it would be an IE11-only issue

Could you share some reproduction code? Not that I have IE11 handy to test 🙈

**Comment by heybourn** [comment] 2020-03-09 22:49
Mind if I email you a link? Would rather keep it off of GitHub as it's residing on my staging server

**Comment by keyurshah** [comment] 2020-03-09 22:50
Thanks for helping out with this @HugoDF .  

I'm getting the same error as @heybourn as well

`Unhandled promise rejection TypeError: Proxy polyfill does not support trap 'originalTarget'`

**Comment by HugoDF** [comment] 2020-03-09 22:56
Is this just happening on Alpine.js load/start? 

Could be the way membrane uses Proxy is not supported by the polyfill. In that case we might have to hunt for a new one.

**Comment by heybourn** [comment] 2020-03-09 22:58
It happens as soon as I hit the site on IE. Not present in Chrome from what I can see.

**Comment by SimoTod** [comment] 2020-03-09 22:58
Not sure if it could be of any help but, as far as I know, the proxy polyfill is quite basic and only supports get, set, apply and construct.
If you try to call another trap, the polifyll will trigger an exception: https://github.com/GoogleChrome/proxy-polyfill/blob/8ad3f2818067ff08456db414b9d17898ae01949a/src/proxy.js#L60

The weird thing is that 'originalTarget' is not an official trap (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler) so it might be the membrane trying to do something custom.

**Comment by SimoTod** [comment] 2020-03-09 23:13
I believe it's due to the handler object using internal variables (https://github.com/salesforce/observable-membrane/blob/4aa7e417755796a99df6d0180d61cba10f7cb991/src/reactive-handler.ts#L58).

The proxy polyfill just assumes that any properties of the handler should be a trap and crashes.

We should try another polyfill or fork the actual one, remove the line triggering an error and let it fail silently for unsupported traps.

It might still not be working properly if it relies on other unsupported traps, though.

**Comment by HugoDF** [comment] 2020-03-10 17:55
How bad would it be to drop IE11 support? Would probably be a deal breaker for a bunch of people.

It sounds like it's going to be hard to make the polyfill and membrane play nicely

**Comment by SimoTod** [comment] 2020-03-10 18:07
Yeah, I couldn't really find another polyfill as good as the one we use. Also, Salesforce's membrane doesn't support IE11 so there are probably other things which won't work.
Sadly, I think a lot of devs still need it because required by their clients.

**Comment by HugoDF** [comment] 2020-03-10 18:59
I guess we could revive the custom proxy for the IE11 build? Probably one for @calebporzio

**Comment by heybourn** [comment] 2020-03-10 19:41
As @SimoTod has mentioned, this need for IE support is solely due to client work. I'd have no issues with Alpine otherwise!

**Comment by HugoDF** [comment] 2020-03-11 21:07
Yep, I think the issue is with `observable-membrane` storing `originalTarget` as a property on the Proxy handler when created.

**Comment by harrysbaraini** [comment] 2020-03-13 14:11
I had to rollback to 2.0.2 version, so IE11 is working again. Only glitch I found is that I need to add `class=""` where `x-bind:class` is used, otherwise the class is not updated:

```
<div class="" x-bind:class="isHidden ? 'hidden' : ''">
   ...
</div>
```

**Comment by heybourn** [comment] 2020-03-15 20:50
> I had to rollback to 2.0.2 version, so IE11 is working again. Only glitch I found is that I need to add `class=""` where `x-bind:class` is used, otherwise the class is not updated:
> 
> ```
> <div class="" x-bind:class="isHidden ? 'hidden' : ''">
>    ...
> </div>
> ```

Downgrading didn't work for me. Are you testing in IE?

**Comment by DannyEndert** [comment] 2020-03-21 19:45
> I had to rollback to 2.0.2 version, so IE11 is working again. Only glitch I found is that I need to add `class=""` where `x-bind:class` is used, otherwise the class is not updated:
> 
> ```
> <div class="" x-bind:class="isHidden ? 'hidden' : ''">
>    ...
> </div>
> ```

Returning to a previous version actually works, but sadly it's not the best way. I think AlpineJS is great, but if I can no longer benefit from updates, it is very sad.

@HugoDF 

Please, please solve the problem!

**Comment by HugoDF** [comment] 2020-03-21 20:34
I've fixed the first issue encountered in a PR but I'm not sure we'll be able to make observable-membrane compatible with IE11, one for @calebporzio though

**Comment by DannyEndert** [comment] 2020-03-21 21:34
> I've fixed the first issue encountered in a PR but I'm not sure we'll be able to make observable-membrane compatible with IE11, one for @calebporzio though

In the meantime, I'm using version 2.0.2. So far it works great!

**Comment by calebporzio** [comment] 2020-03-29 05:07
Sorry for this issue folks. It's because of a Proxy trap that observable-membrane uses but isn't supported in the proxy-polyfill.

I will do my best to get IE11 back working as best and fast as I can. There are no ideal solutions at the moment, but I will re-surface with something soon.

**Comment by JeanPaulvB** [comment] 2020-03-29 10:22
Perhaps I'm overlooking something (I just got started with Alpine), but I can't even get the following to work at the moment using [https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js](https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js) on _any_ browser:

```
<div x-data>
  <button  class="btn btn-secondary" @click="$el.innerHTML = 'Yes, it works'">Test if Alpine.js is loaded</button>
</div>
<br>
<br>

<div x-data="{ open = false }">
  <input class="form-input" type="text" name="firstName" id="firstName" autofocus="autofocus" required="required" />
  <div x-show="open">
    Not valid
  </div>
</div>
```
### [See codepen](https://codepen.io/qntl/pen/xxGmvbR)

I'm getting the following error in console:

> Uncaught (in promise) SyntaxError: Invalid shorthand property initializer
>     at new Function (<anonymous>)
>     at saferEval (alpine.js:109)
>     at new Component (alpine.js:1227)
>     at Object.initializeComponent (alpine.js:1618)
>     at alpine.js:1566
>     at alpine.js:1582
>     at NodeList.forEach (<anonymous>)
>     at Object.discoverComponents (alpine.js:1581)
>     at Object.start (alpine.js:1565)

Note how the upper button **does** work but the text below the input field still shows.

**Comment by calebporzio** [comment] 2020-03-29 19:29
Ok, this should be fixed.

I will be better about testing future releases in IE11 (probably just purchase a subscription to lambda test and test there manually for now.). At some point, it'd be nice to have automated IE11 tests, but I'd like to hold off on the extra overhead with those kinds of tests.

Sorry about this. Thanks, everyone for chiming in and pitching in.

**Closed by calebporzio** 2020-03-29 19:29 UTC
