### ISSUE TITLE
replacing data with object is not working

### ISSUE THREAD

**Issue by sibbngheid** [alpinejs/alpine#36] opened 2019-12-25 02:12 UTC
I want to replace my data item with a object but it is not working.

Repro:
https://codesandbox.io/s/staging-tdd-pgd3t

**Comment by calebporzio** [comment] 2020-01-03 04:15
Here's a reproduction of your problem:

```html
        <div x-data="{ open: false }">
            <div x-text="open.data"></div>
            
            <button x-on:click="open = { data: 'test' }">
              Set object
            </button>
          </div>
```

The problem is that you are completely overwriting the "open" property, instead of mutating a property on it.

You are destroying the observability of the change, therefore the change isn't reflected.

Have you encountered this issue in a real-life scenario? If so, please paste in the code, so I can see when this behavior is desired.

Closing for now. Re-open if you want.

Thanks!

**Closed by calebporzio** 2020-01-03 04:15 UTC
