### ISSUE TITLE
Alpine Js does not sync data for x-text and x-model, if used in a loop on a table row

### ISSUE THREAD

**Issue by mansoorkhan96** [alpinejs/alpine#1191] opened 2021-03-19 08:20 UTC
I am trying to loop over employees array and I want to show employee salary and an input field to edit employee salary. The problem is that Alpine does not sync data from input field to the text element.
What I am trying is:

```
<tbody>
<template x-for="employee in employees">
    <tr>
        <td>
            <input x-model="employee.basic_salary">
        </td>
        <td x-text="employee.basic_salary"></td>
    </tr>
</template>
</tbody>

<script>
function data() {
    return {
        employees: [
            {id:1, basic_salary: 6000},
            {id:2, basic_salary: 7000},
        ]
    }
}
</script>
```

I tried to move the `<tbody>` inside the `<template>` and it works but It breaks the table so it does not works as expected :( Here is what i tried:

```
<template x-for="employee in employees">
    <tbody>
        <tr>
            <td>
                <input x-model="employee.basic_salary">
            </td>
            <td x-text="employee.basic_salary"></td>
        </tr>
    </tbody>
</template>

<script>
function data() {
    return {
        employees: [
            {id:1, basic_salary: 6000},
            {id:2, basic_salary: 7000},
        ]
    }
}
</script>
```

One should never put a loop before `<tbody>`

**Comment by ryangjchandler** [comment] 2021-03-19 09:02
`x-model` assignments are quite naive so you need to do `(employee, index) in employees` inside your loop and then `employees[index].name` in the `x-model`.

**Comment by mansoorkhan96** [comment] 2021-03-19 09:04
@ryangjchandler I also tried that but it does not work.

**Comment by SimoTod** [comment] 2021-03-19 09:13
@mansoorkhan96 Ryan's suggestions works for me: https://codepen.io/SimoTod/pen/yLVdxPw

**Comment by mansoorkhan96** [comment] 2021-03-19 09:18
@ryangjchandler @SimoTod I forgot to tell you guys that i am using DataTables

**Comment by mansoorkhan96** [comment] 2021-03-19 09:18
@ryangjchandler @SimoTod I forgot to tell you guys that i am using DataTables

**Comment by ryangjchandler** [comment] 2021-03-19 09:24
@mansoorkhan96 Have you got a CodePen / fiddle with a minimal reproduction?

**Comment by SimoTod** [comment] 2021-03-19 09:26
@mansoorkhan96 In that case, I wouldn't use x-for since DataTables is likely to change move your HTML.
It's probably easier to use DataTables itself: https://datatables.net/examples/data_sources/js_array.html 
You can create a function in your component that generates the expected output from the source array. 
And, if you need it, renders to format specific cells: https://datatables.net/manual/data/renderers.

**Comment by mansoorkhan96** [comment] 2021-03-19 09:36
> @mansoorkhan96 Have you got a CodePen / fiddle with a minimal reproduction?

https://codepen.io/mansoor-khan-aadeez/pen/gOLNdKo

**Comment by mansoorkhan96** [comment] 2021-03-19 09:37
> @mansoorkhan96 In that case, I wouldn't use x-for since DataTables is likely to change move your HTML.
> It's probably easier to use DataTables itself: https://datatables.net/examples/data_sources/js_array.html
> You can create a function in your component that generates the expected output from the source array.
> And, if you need it, renders to format specific cells: https://datatables.net/manual/data/renderers.

ok let me try these.

**Comment by mansoorkhan96** [comment] 2021-03-19 09:40
And in the last I would be adding another field for `salary_bonus`. So my goal is to to show `x-text="basic_salary+salary_bonus"`, for each row.

**Comment by mansoorkhan96** [comment] 2021-03-19 09:40
And in the last I would be adding another field for `salary_bonus. So my goal is to to show x-text="basic_salary+salary_bonus", for each row.

**Comment by mansoorkhan96** [comment] 2021-03-19 10:02
Thanks @ryangjchandler  and @SimoTod 
Looks like i should stick with only DataTables for this use case.

**Comment by HugoDF** [comment] 2021-03-22 14:07
@mansoorkhan96 good to close this issue then?

**Closed** 2021-03-27 06:21 UTC
