### ISSUE TITLE
Unable to bind key to uuid with hyphens or underscore

### ISSUE THREAD

**Issue by tanthammar** [alpinejs/alpine#511] opened 2020-05-21 12:53 UTC
My db has Uuid:s with a prefix. The Uuid:s also contains underscores.

An example: "org--3y__-fLqqwF8ZvKYzmp7"

I am unble to use the uuid to bind as key for loops.
In this example I get an error saying that `org-` is undefined.

**Comment by HugoDF** [comment] 2020-05-21 14:58
Would you be able to provide a codepen to reproduce this?

**Comment by tanthammar** [comment] 2020-05-21 15:08
I do not have a codepen account :)

but just add :key="org--3y__-fLqqwF8ZvKYzmp7" to any alpine component and you'll get the error.

If you wrap the uuid with `''` the error goes away. But that does not seem to be the correct way.
so `:key="'org--3y__-fLqqwF8ZvKYzmp7'"` gives no error.

```info
VM12224:3 Uncaught (in promise) SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at saferEval (alpine.js:101)
    at Component.evaluateReturnExpression (alpine.js:1551)
    at handleAttributeBindingDirective (alpine.js:518)
    at alpine.js:1514
    at Array.forEach (<anonymous>)
    at Component.resolveBoundAttributes (alpine.js:1500)
    at Component.initializeElement (alpine.js:1419)
    at alpine.js:1403
    at alpine.js:1393
```

**Comment by HugoDF** [comment] 2020-05-21 15:11
Sure so when you `x-bind:key="org--3y__-fLqqwF8ZvKYzmp7"` what's inside `""` is evaluated as a JavaScript/Alpine.js expression, in this case, there's no variable named `org--3y__-fLqqwF8ZvKYzmp7`, hence the crash.

That's actually why using quotes fixes the issue `:key="'org--3y__-fLqqwF8ZvKYzmp7'"` because now what's getting evaluated in `""` is the string `'org--3y__-fLqqwF8ZvKYzmp7'`.

Closing this, feel free to reopen if the explanation doesn't make sense.

**Closed by HugoDF** 2020-05-21 15:11 UTC

**Comment by tanthammar** [comment] 2020-05-21 15:12
Ah, of course...
