### ISSUE TITLE
Performance issues on Firefox with components inside loop

### ISSUE THREAD

**Issue by zepfietje** [alpinejs/alpine#804] opened 2020-10-06 18:50 UTC
Firefox seems to have terrible performance compared to Chrome and Safari when it comes to rendering nested Alpine components in a loop.
Unfortunately, I haven't been able to create a minimal reproducible example.
However, I'll post a short description of the situation for now.

When adding items to an `x-for` loop which contains other Alpine components (input with custom handling), Firefox renders the added items immediately for the first few added.
However, when adding more, it hangs for a few seconds or becomes completely unresponsive.

Not sure if there's anything to be done on the Alpine side, but it would be great if there'd be ways to improve on this issue. Currently, I'm entirely blocked on some functionality, since it's just completely unusable on Firefox.

Looking forward to hearing any thoughts.

**Comment by HugoDF** [comment] 2020-11-03 16:56
To clarify, you've got a component that has an `x-for` and then inside the `x-for` you're initialising new components?

Something like:

```html
<div x-data="{ els: [1, 2, 3] }">
  <template x-for="el in els">
    <div x-data>do something</div>
  </template>
</div>
```
?

**Comment by zepfietje** [comment] 2020-11-03 21:24
@HugoDF, thanks for your comment.
I'm trying hard to create a minimal reproducible code snippet. However, I haven't been able to experience the performance issue with a simple snippet like you posted above.

Since I've been jumping back and forth between a Livewire + Alpine and Alpine only implementation (IIRC both showed the performance issue), I can't really pinpoint the exact cause.

I just tried to strip my code down to a minimum, while still keeping the issue. What I found is that the nested Alpine component didn't necessarily have to be an Alpine component (could be just regular HTML elements) to show the issue. Also, randomly removing DOM nodes seemed to improve the performance.

Another important observation is the fact that the Livewire component is wrapped in another Livewire component (which functionally didn't do anything after stripping it down). However, removing the parent Livewire component also did seem to improve performance.

Sorry for all the vagueness, but I just haven't been able to find the direct cause of the issue. I do feel like Alpine performance in Firefox is a problem in general when you have a rather extensive UI. If you think the issue could be on the Livewire side, let me know. But I do think it's related to Alpine, since I encountered the issue without Livewire too.

Thanks again for your help, really appreciate any input to fix this issue.

**Comment by HugoDF** [comment] 2020-11-03 21:26
Hmmm unfortunately we're not going to be able to do anything without sample code that grinds Firefox to a halt

**Comment by KevinBatdorf** [comment] 2020-11-03 21:29
Someone else mentioned something similar with older versions of jQuery. Maybe related?

https://github.com/alpinejs/alpine/issues/819

**Comment by zepfietje** [comment] 2020-11-03 21:44
> Hmmm unfortunately we're not going to be able to do anything without sample code that grinds Firefox to a halt

Yeah, I totally understand.
Will keep trying to create a sample with just Alpine (no Livewire) which shows the issue.

**Comment by zepfietje** [comment] 2020-11-03 21:49
> Someone else mentioned something similar with older versions of jQuery. Maybe related?
> 
> #819

Not sure.
I did see that issue. However, I'm not using jQuery (or any other JS library) and my code doesn't contain any errors.

**Comment by MarcGodard** [comment] 2021-02-16 12:36
I am also seeing these performance dips in firefox. Will also investigate.

**Comment by zepfietje** [comment] 2021-03-31 12:28
It's been some time, but I've now got it running in production (managed to improve performance a slight bit). However, it's still way too slow in Firefox (Safari and Chrome are ok).

Steps to reproduce the issue:
1. Go to https://picci.app/create.
2. Fill out the title field.
3. Press the "Continue" button.
4. Select a couple of dates (let's say 5).
5. Press the "Edit times" button.
6. Add about 4 more times using the "Add more times" button.
7. Press the "Edit times per date" button.
8. Try adding more times to any date using the "Add more times" button.
9. Experience long delays before new inputs are actually added.

Adding items to the list is done using Livewire. However, this truly is an Alpine issue, as there's huge differences between browsers. Also, Firefox seems to be under such a heavy load that it can't even open the developer tools properly.

@HugoDF @KevinBatdorf, let me know when you've found the time to check this out.

**Comment by HugoDF** [comment] 2021-03-31 17:41
> Adding items to the list is done using Livewire. However, this truly is an Alpine issue, as there's huge differences between browsers.

I've had a look and it seems Livewire is what adds the "date inputs" so not sure why you think it's an Alpine issue?

What happens if you remove the Alpine directives for that specific piece of code? Does the code start running without issue?

**Comment by zepfietje** [comment] 2021-03-31 20:10
> I've had a look and it seems Livewire is what adds the "date inputs" so not sure why you think it's an Alpine issue?

Thanks! Indeed, Livewire is used to add times to the list. However, I've previously built the flow without Livewire (just Alpine) and the performance issue also existed.

Furthermore, I used to have the autoresizing textarea for description (built with Alpine) on the same page as the date picker component. This resulted in similar performance issues with Firefox (other browsers were smooth) when typing in the textarea. I have to admit I'm not 100% sure it's an Alpine issue, but to me everything points in that direction.

> What happens if you remove the Alpine directives for that specific piece of code? Does the code start running without issue?

Just tried, removed all `x-` directives from the `.time-input` class component, but I don't see any performance improvement.

**Comment by HugoDF** [comment] 2021-04-02 17:50
> Just tried, removed all `x-` directives from the `.time-input` class component, but I don't see any performance improvement.

Interesting, how about if you don't load the Alpine script itself? Wondering if it could be Alpine's mutation observer causing issues.

**Comment by zepfietje** [comment] 2021-04-04 12:43
> Interesting, how about if you don't load the Alpine script itself? Wondering if it could be Alpine's mutation observer causing issues.

It doesn't seem to make any difference (or it's just barely noticeable).

**Comment by SimoTod** [comment] 2021-04-04 13:45
If you don't load alpine and you have the same issues, it's probably another script in your page

**Comment by HugoDF** [comment] 2021-04-11 14:58
@zepfietje if removing Alpine doesn't fix the issue, it's unlikely that the issue is caused by Alpine (by elimination)

Tempted to close this issue since we haven't been able to repro/narrow down to an Alpine issue, it's probably something else (Livewire, some other scripts) being used in conjunction with Alpine.

**Comment by zepfietje** [comment] 2021-04-11 15:05
Yes, I understand.
I'm using nothing else besides Alpine and Livewire, so probably it's a Livewire issue then.

However, I'd like to try one more thing before closing this issue.
I'll try to reproduce a similar issue I had some time ago:

> Furthermore, I used to have the autoresizing textarea for description (built with Alpine) on the same page as the date picker component. This resulted in similar performance issues with Firefox (other browsers were smooth) when typing in the textarea.

If that issue occurs without loading Livewire, there might still be an issue with Alpine and Firefox.
Will report back ASAP.

**Comment by calebporzio** [comment] 2021-04-14 13:45
Thanks everyone, closing this as Alpine is not the issue. If you believe Livewire is, please open an issue on that repo with your findings, a link back to this issue, and simple reproducible steps to reproduce for others to more easily pitch in. Thanks!

**Closed by calebporzio** 2021-04-14 13:45 UTC
