### ISSUE TITLE
$attributes->merge doesn't not update classes when the default appears further below in .css file

### ISSUE THREAD

**Issue by KujengaDigital99** [alpinejs/alpine#1239] opened 2021-04-07 21:33 UTC
$attributes->merge needs to overwrite the default style being replaced instead of add at the end. 

While this works most of the time... the issue starts when the style added to the current classes list of x-component appears before the default style in the compiled stylesheet.

So if you used .bg-indigo-500 as a default class and $attributes->merge(['class' => 'bg-green-500']) is used... .bg-indigo-500 will always show because in the compiled tailwind css file... .bg-indigo-500 appears at 3881 and .bg-green-500 appears at 3781

![image](https://user-images.githubusercontent.com/67253254/113937121-fac79700-97f8-11eb-83d3-84d29cc31b7d.png)

**Comment by SimoTod** [comment] 2021-04-08 05:16
From the screenshot it doesn't seem you are using Alpine to merge those lists, can you post an example to reproduce the issue? You should be able to do what you need using `:class`.

**Comment by HugoDF** [comment] 2021-04-11 14:54
Closing since it's probably not an Alpine bug, as @SimoTod said if you encounter this again, probably a better fit for a [discussion](https://github.com/alpinejs/alpine/discussions/new)

**Closed by HugoDF** 2021-04-11 14:54 UTC
