### ISSUE TITLE
IE11, SCRIPT1002: Syntax error on then

### ISSUE THREAD

**Issue by vamone** [alpinejs/alpine#699] opened 2020-08-11 16:48 UTC
Hello, 

Trying to make it work on IE11. It seems to work when only inline modifications are made but when you are writing a little bit more complex code with fetch and then etc, it seems that IE11 does not like it. 

Can anyone help me here? Do I miss some polifils or so?

**Comment by ryangjchandler** [comment] 2020-08-11 17:00
@vamone fetch & promise based libraries aren't supported in IE11 without errors - you need to add some polyfills for those or use regular XHR instead.

**Comment by vamone** [comment] 2020-08-11 17:06
> @vamone fetch & promise based libraries aren't supported in IE11 without errors - you need to add some polyfills for those or use regular XHR instead.

Than you for your comment. 

I'm using this script provided by the creators and it still not working.
<script nomodule src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.5.0/dist/alpine-ie11.min.js" defer></script>

Do you know some specific libraries for fetch and promise?

**Comment by ryangjchandler** [comment] 2020-08-11 17:09
That script doesn't include a Fetch polyfill because Fetch isn't used in the Alpine core. 

I'd use this one: https://github.com/github/fetch

**Comment by SimoTod** [comment] 2020-08-11 17:10
The error is not in the script but in the code you added in your page.
IE11 doesn't support fetch so you can't use it unless you include the needed polyfill to support your custom code.

**Comment by HugoDF** [comment] 2020-08-13 17:50
I'll close this for now since it's probably not being caused by Alpine.js itself

Feel free to reopen.

**Closed by HugoDF** 2020-08-13 17:50 UTC
Labels: question
