### ISSUE TITLE
See if there are any ideas worth borrowing from Mavo 

### ISSUE THREAD

**Issue by carlmjohnson** [alpinejs/alpine#425] opened 2020-04-26 16:36 UTC
Mavo is another Angular-inspired HTML-first framework: https://mavo.io/ Its approach seems to be more all-in-one than Alpine, but it’s probably worth reading the docs and seeing if there’re any ideas worth stealing.

**Comment by mblarsen** [comment] 2020-04-27 14:48
Yeah it has been around a long time, and I was wondering if there any experiences to be learned from it. 

Aside: litte cool widget built with Mavo https://css.land/lch to illustrate lch

**Comment by HugoDF** [comment] 2020-04-27 15:01
Interesting project, honestly I like that Alpine mostly works like I've come to expect from Vue/React with a restricted feature set (eg. No templating, just directives)

**Comment by carlmjohnson** [comment] 2020-04-27 17:40
Yeah, reading through it, the only thing that really jumps out to me are maybe `property` and `mv-storage`. But they're both coming from the point of view of providing a rich framework instead of letting users build up from primitive pieces.

**Comment by SimoTod** [comment] 2020-04-28 19:44
> Aside: litte cool widget built with Mavo https://css.land/lch to illustrate lch

A bit less refined since I didn't have much time, but this would be the Alpine version https://codepen.io/SimoTod/full/RwWgWMo

**Comment by HugoDF** [comment] 2020-05-02 18:56
> Yeah, reading through it, the only thing that really jumps out to me are maybe `property` and `mv-storage`. But they're both coming from the point of view of providing a rich framework instead of letting users build up from primitive pieces.

I think persistence is not likely to be something Alpine core ever does, you can mostly reproduce this functionality using `localStorage` in `x-data` + `$watch` in `x-init`, obviously a bit of boilerplate but it's likely to be a pretty commong "syncing" pattern that applies to the URL, localStorage, even a backend server if you wanted.

As it stands, are we ready to close this issue? Might be worth revisiting for v3

**Closed** 2020-05-02 23:27 UTC
