### ISSUE TITLE
Delete operator doesn't work directly on data objects

### ISSUE THREAD

**Issue by lancepioch** [alpinejs/alpine#118] opened 2020-01-20 20:41 UTC
Version: 1.9.3

Note: this is inside a v-for

Workaround: Create temp variable and then reassign it

Data Variables (`vars`): https://github.com/lancepioch/tree/commit/3c6a4b59f8b80cbb2f07a64f391a2adbb88056f1#diff-45badbdf21eeef095a1bc3568c3346bfR96

Click Event with Workaround: https://github.com/lancepioch/tree/commit/3c6a4b59f8b80cbb2f07a64f391a2adbb88056f1#diff-45badbdf21eeef095a1bc3568c3346bfR159

**Comment by calebporzio** [comment] 2020-01-21 18:13
This is because there is no delete trap set up on the observable proxy object in component.js.

This is something I'll be looking into soon (making the proxy more reactive to deletions, and other things like array manipulations)

**Comment by SimoTod** [comment] 2020-04-11 16:26
The new membrane should support the delete trap.
See https://codepen.io/SimoTod/pen/wvKBRoO

Known limits: 
- the ie11 version does not support it due to the proxy polyfill (it's not possible to polyfill the delete trap).
- delete needs to use the items[i] syntax which means that stuff like `delete item` won't work. This is not really caused by the delete trap but by the current x-for implementation as mentioned in #144.

Shall we close this issue?

**Comment by ryangjchandler** [comment] 2020-04-11 16:33
Yeah, I'll close this issue now. Thanks for the update on this @SimoTod.

**Closed by ryangjchandler** 2020-04-11 16:33 UTC
Labels: bug
