### ISSUE TITLE
Events stop firing when I "change a page"

### ISSUE THREAD

**Issue by spapas** [alpinejs/alpine#413] opened 2020-04-23 19:50 UTC
This is not easy to describe so I've created a small jsfiddle with the required code to reproduce the problem:

https://jsfiddle.net/yn4h37pf/

What happens is that I want to implement pagination in a list of items and have each of these items respond to a click event. When you click on the numbers you'll see the event fire in the console log. However if you press "Next page" to load the next page you'll see that although it displays the next 3 numbers, when you click on their buttons nothing will happen. Even if you press previous page to return to the 1st page you still won't get any output in the console.

Am I doing something wrong or maybe this is something not supported at all or this is a bug ?

TIA !

**Comment by codeMonkeysBe** [comment] 2020-04-23 21:30
I'm experiencing the exact same behaviour. Also paginating things the same way. However it does work without x-for. https://jsfiddle.net/L6gbdn9z/

**Comment by SimoTod** [comment] 2020-04-23 22:51
Yeah, it seems to be a bug. The x-for doesn't bind your listener when updating the list, only the first time when creating it.

https://github.com/alpinejs/alpine/blob/master/src/directives/for.js

**Comment by ryangjchandler** [comment] 2020-04-24 10:18
It seems to be working fine for me...

https://streamable.com/il6c14

**Comment by spapas** [comment] 2020-04-24 10:49
@ryangjchandler are you using the same fiddle i posted? Also which browser you are using? I tried it in Chrome Firefox and edge and got the same non-working behavior to all three!

**Comment by ryangjchandler** [comment] 2020-04-24 10:50
Yeah I'm using the same fiddle in Firefox, tested in Chrome and works fine too.

**Comment by spapas** [comment] 2020-04-24 10:54
I really don't know why it doesn't work in my case and works in your case. This is really crazy. 

However I am not the only one experiencing problems with that - two other commenters agreed that the behavior is problematic.

**Comment by ryangjchandler** [comment] 2020-04-24 11:00
I've modified your original fiddle, https://jsfiddle.net/2ha9k15w/1/

There is a span in the top right that shows the current number, does this work?

**Comment by spapas** [comment] 2020-04-24 11:13
No unfortunately it has exactly the same behavior:

https://imgur.com/a/pp9iXPG

When I click the numbers without "changing the page" it works fine, after I change the page it stops working !

**Comment by ryangjchandler** [comment] 2020-04-24 11:20
This is super strange... are there any errors in your console?

**Comment by spapas** [comment] 2020-04-24 11:29
No errors just some (yellow) warnings. Also please notice that I made this fiddle because my original app wasn't working also. You can take a look at it here if you want: https://cpus.netlify.app/

You'll see that when you click the `+` for the items on the first page they will be copied to the right. When you change page it won't work anymore :(

**Comment by ryangjchandler** [comment] 2020-04-24 11:48
I can reproduce on that site, not on the fiddle. Very strange indeed!

**Comment by SimoTod** [comment] 2020-04-24 11:49
I can confirm that neither the original jsfiddle nor the new one work for me.

Looking at the source code it kind of makes sense (I'm not sure how you hacked that Ryan, maybe there is a bug within the bug, hahaha).

So basically x-for initialise the list, since it's the first time and the next element doesn't have the __x_for_key attribute, this line https://github.com/alpinejs/alpine/blob/master/src/directives/for.js#L18 evaluates to true. It means that the initial elements use component.initializeElements (which initialise any listeners as well).
The second time, since there's an element with __x_for_key, the above condition resolves to false so we run the second branch of the `if`. Even if the lookahead fails, the code is still using component.updateElements for something that is, in reality, a new element.
updateElements does not initialise any listeners by design (otherwise we would end up with duplicated handlers every time alpine refreshes).

I think it's fixable (we should shuffle the code a bit a lookahead failure fails should fall in the second branch of the `if` condition) but it looks like a bug for now.

**Comment by muzafferdede** [comment] 2020-04-24 12:06
Maybe old version of Alpine cached in Ryan's case? Not working for me as well.

**Comment by ryangjchandler** [comment] 2020-04-24 12:16
> Maybe old version of Alpine cached in Ryan's case? Not working for me as well.

Tried a hard refresh too and was still working on the Fiddle.

**Comment by SimoTod** [comment] 2020-04-24 12:19
I think I have a fix for this, I'll tidy up my code and send a PR after work.

**Comment by SimoTod** [comment] 2020-04-24 12:27
@spapas in the meantime, can you test https://cdn.jsdelivr.net/gh/SimoTod/alpine@feature/x-for-bindings/dist/alpine.min.js for me please? I'll be back at around 5-ish (GTM) in case you have any feedback.

**Comment by spapas** [comment] 2020-04-24 12:52
@SimoTod yes this seems to be working great: https://jsfiddle.net/n6mvoer3/ thank you!

**Comment by willcosgrove** [comment] 2020-05-02 23:59
I'm having this same issue, but it's happening even without being inside of an `x-for`.  I've got turbolinks on the page, and any time I change pages, event handlers don't get wired up on new components.  I tried @SimoTod's test build but the problem still persists for me.  I'm still new to alpine so I don't have any suggestions on what might be happening.  I also don't know how to easily reproduce the issue in a fiddle since it involves turbolinks and navigating to another page.

**Comment by SimoTod** [comment] 2020-05-03 00:08
This PR doesn't address turbolinks. It was a bug on the x-for tag (change page didn’t mean navigating with the browser, it was a javascript pagination on an existing array).
There is another PR addressing some turbolinks bugs not sure if it would fix your case but you can add more details on that thread. (I'll post the link in 2 minutes)

**Closed** 2020-05-08 14:47 UTC
