### ISSUE TITLE
2.3.0 regression with x-bind / x-model and hidden inputs

### ISSUE THREAD

**Issue by gilbert** [alpinejs/alpine#404] opened 2020-04-22 02:52 UTC
- [2.2.5 x-model](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwggFYtJDIwOxc3GwxcdyMwFQA+QS0RcSkUpTpcwQjzaQAPAFokBngGZRBgaSRUaQByYqbpAF9U3OlpQXcJAFcZeABPCQgarDIkUzyQaUZmGtHxlWlp5bGINfMXAYmVNbKAI3cG3ah9mqQuuh7hCQY7ssRi+GvU9LBHuhy6dMKf04kBgCDIvCo6AADKgAGxQ0ow2EAZhA7UI9CYLHQSU4PD4EAE6DRGJAi2xmFgYCoxHx-HgrDRAF12kA) – Works
- [2.3.0 x-model](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwAZgwABi0kMjA7FzcbDFx3IzAVAD5BLRFxKTSlOnzBKPNpAA8AWiQGeAZlEGBpJFRpAHJSlukAX3T86WlBdwkAVxl4AE8JCDqsMiRTApBpRmY68cmVaVnViYgN8xchqZUNioAjdyb9qEO6pB66PuEJBgeKxFL4W-TMsGe6PLomWKAM4kBgCDIvCo6DCqAAbMEQJ1CPQmCx0ClODw+BABOgkSiQMt0ZhYGAqMRsfx4KwkQBdTpAA) – Throws [TypeError: Type error]

Same respective behaviors when you replace `x-model` with `x-bind:value`

**Comment by sjelfull** [comment] 2020-04-22 05:13
I _think_ I'm seeing the same thing. After upgrading, i'm seeing problems in parts of my app that uses hidden inputs.

**Comment by SimoTod** [comment] 2020-04-22 07:12
It should be the same regression discussed here #401

**Comment by sjelfull** [comment] 2020-04-22 08:48
@SimoTod Yep, looks like it from checking exception reports.

**Comment by ryangjchandler** [comment] 2020-04-22 08:56
@sjelfull , would it be okay to close this issue and move discussion across to the one @SimoTod mentioned?

**Comment by sjelfull** [comment] 2020-04-22 08:58
Yep, I don't mind.

**Comment by ryangjchandler** [comment] 2020-04-22 08:59
Perfect, thanks @sjelfull. I'll close this issue now and keep track of anything else on #403 or #401 . Thanks! :)

**Closed by ryangjchandler** 2020-04-22 08:59 UTC

**Comment by 03juan** [comment] 2020-04-22 09:01
Strangely I can't seem to reproduce the TypeError on Chrome in windows on the provided 2.3.0 code

**Comment by sjelfull** [comment] 2020-04-22 09:06
@03juan As far as I can tell it only affects Safari / Mobile Safari, where Chrome on iOS is included.

**Comment by gilbert** [comment] 2020-04-29 01:11
It seems like this error is [still occuring](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwAZgwARi0kMjA7FzcbDFx3IzAVAD5BLRFxKTSlOnzBKPNpAA8AWiQGeAZlEGBpJFRpAHJSlukAX3T86WlBdwkAVxl4AE8JCDqsMiRTApBpRmY68cmVaVnViYgN8xchqZUNioAjdyb9qEO6pB66PuEJBgeKxFL4W-TMsGe6PLomWKAM4kBgCDIvCo6AADKgAGzBECdQj0JgsdApTg8PgQAToZGokDLDGYWBgKjEHH8eCsZEAXU6QA)?

**Comment by SimoTod** [comment] 2020-04-29 07:27
Yes, it's still happening. #401 wasn't enough to cover your use case. There's already a pending PR in review (#424) but it hasn't been merged yet.

**Comment by 03juan** [comment] 2020-04-29 08:22
That's unfortunate. I don't have Safari to test on, so I could only fix my particular text-selection issue caused by the original regression. Hope the next fix clears things up for everyone!
