### ISSUE TITLE
MutationObserver is never disconnect

### ISSUE THREAD

**Issue by var-che** [alpinejs/alpine#446] opened 2020-05-01 23:34 UTC
Hi there

I have noticed that MutationObserver is never disconnected, which in most cases result in the terrible memory performance.  Are you planning to address that in the near future? What are your thoughts on that?

**Comment by SimoTod** [comment] 2020-05-02 08:29
Do you have an example to replicate the issue? Can you provide more details please? Thanks

**Comment by var-che** [comment] 2020-05-02 08:31
Its in the SRC/index.js.
Find MutationObserver instance. It's there.

**Comment by SimoTod** [comment] 2020-05-02 08:39
yeah, I know where the mutation observer is.
I wonder if you have an example of where it would be an issue.
It's an object so it stays in memory as long as it's referenced by the page like other objects, right?
Have you experienced slowness or other stuff? Do you have any concern you can explain?Alternatives to provide? etc. 
Otherwise it's not clear what the issue refers to so it's hard to understand if it requires a fix or not.  
Thanks

**Comment by SimoTod** [comment] 2020-05-02 08:42
P.s. the mutation observer need to run continuously because it's how the author designed the library. it will intercept new elements added to the DOM and instantiate their reactivity.
When you navigate to a different page, the garbage collector will eventually trash the object.

**Comment by var-che** [comment] 2020-05-02 08:42
I don't have a concrete example, no. I was just addressing the fact that if the object does not get disconnected, it can cause the issue. 
I hope that you understand my concern which is the point of opening this issue.

**Comment by mblarsen** [comment] 2020-05-02 08:43
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/disconnect)

> If the element being observed is removed from the DOM and then subsequently released by the browser's garbage collection mechanism, the MutationObserver is likewise deleted.

So it shouldn't be needed.

**Comment by HugoDF** [comment] 2020-05-08 22:27
Thanks @var-che @mblarsen 

Are we good to close this issue? Doesn't sound like there's a concrete bug or reproduction case mentioned.

**Comment by HugoDF** [comment] 2020-05-09 16:20
Closing this for now, feel free to reopen if it's actually causing a reproducible issue 😄 thanks for the discussion everyone.

**Closed by HugoDF** 2020-05-09 16:20 UTC
